BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "beaglebone_optimal"
BBFILE_PATTERN_beaglebone_optimal = "^${LAYERDIR}/"
BBFILE_PRIORITY_beaglebone_optimal = "8"

LAYERVERSION_beaglebone_optimal = "1"
LAYERSERIES_COMPAT_beaglebone_optimal = "scarthgap"

LAYERDEPENDS_beaglebone_optimal = "core yoctobsp"
