BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "beaglebone_optimal_product"
BBFILE_PATTERN_beaglebone_optimal_product = "^${LAYERDIR}/"
BBFILE_PRIORITY_beaglebone_optimal_product = "9"

LAYERVERSION_beaglebone_optimal_product = "1"
LAYERSERIES_COMPAT_beaglebone_optimal_product = "scarthgap"

LAYERDEPENDS_beaglebone_optimal_product = "core yocto-bsp beaglebone_optimal qt6-layer"

BEAGLEBONE_OPTIMAL_PRODUCT_LAYERDIR := "${LAYERDIR}"

BSPDIR ??= "${@os.path.abspath(os.path.join(d.getVar('LAYERDIR'), '..'))}"
