#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

trap 'reboot -f'   TERM
trap 'halt -f'     USR1
trap 'poweroff -f' USR2

while true; do
	setsid cttyhack sh
	echo "Console sh exited with $?, respawning..."
	sleep 1
done
