#@TYPE: Machine
#@NAME: beaglebone-black-optimal-tiny
#@DESCRIPTION: Tiny BeagleBone Black machine for the initramfs path

require conf/machine/include/arm/armv7a/tune-cortexa8.inc

DEFAULTTUNE ?= "cortexa8hf-neon"

SERIAL_CONSOLES ?= "115200;ttyS0"
INITRAMFS_IMAGE = "core-image-optimal-tiny-initramfs"
INITRAMFS_IMAGE_BUNDLE = "1"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto-tiny"
PREFERRED_VERSION_linux-yocto-tiny ?= "6.6%"
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot"

KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE = "ti/omap/am335x-boneblack-optimal-tiny.dtb"

SPL_BINARY = "MLO"
UBOOT_SUFFIX = "img"
UBOOT_MACHINE = "am335x_evm_defconfig"

MACHINE_FEATURES = ""
MACHINE_ESSENTIAL_EXTRA_RDEPENDS = ""
MACHINE_EXTRA_RRECOMMENDS = ""

EXTRA_IMAGEDEPENDS += "virtual/bootloader"
